# Testing docker build push wit h remote
name: Test Docker Build
on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yaml'

jobs:
  build:
    uses: exploring-gh-organizations/called/.github/workflows/docker.yaml@main
    with:
      repo-name:: "code-quality"
      context: "."
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
